# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forge < Formula
  desc "Forge is a secure, portable AI Agent runtime. Run agents locally, in cloud, or enterprise environments without exposing inbound tunnels."
  homepage "https://github.com/initializ/forge"
  version "0.19.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/initializ/forge/releases/download/v0.19.0/forge-Darwin-x86_64.tar.gz"
      sha256 "b29eeb5e2a933d7596f4d5c93dbc874dee06c7ad68882ecbd1e727ee012e6316"

      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/initializ/forge/releases/download/v0.19.0/forge-Darwin-arm64.tar.gz"
      sha256 "9fc37fbdf77168ffda1d675fd90661f37b95c4c1451f8394523f353ecece69c6"

      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/initializ/forge/releases/download/v0.19.0/forge-Linux-x86_64.tar.gz"
      sha256 "7ed76bd540cf98bebda202d9d3d9380270ed226af0491804f912f94a0a72ab0a"
      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/initializ/forge/releases/download/v0.19.0/forge-Linux-arm64.tar.gz"
      sha256 "e8cd4c58d64892bce862d56ba328d5423d1bb3d9eca0854109671754723a4a3f"
      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  test do
    system "#{bin}/forge", "--version"
  end
end
