# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Initializ < Formula
  desc "Initializ platform CLI for CI pipelines"
  homepage "https://initializ.ai"
  version "0.3.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/initializ/cli/releases/download/v0.3.3/initializ_darwin_amd64.tar.gz"
      sha256 "a0d8ed6b0119a20cf6bd9369b4c0d378bfda836e3714c75835bc0e0dc0248ff4"

      define_method(:install) do
        bin.install "initializ"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/initializ/cli/releases/download/v0.3.3/initializ_darwin_arm64.tar.gz"
      sha256 "8635a431fe15efefa49bbd8eea978c957ae1588f7a8094177e38938ba753609f"

      define_method(:install) do
        bin.install "initializ"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/initializ/cli/releases/download/v0.3.3/initializ_linux_amd64.tar.gz"
      sha256 "b45486a16ca32ab430ffef49988454c6e0f517b1828cacf4706014049b451b90"
      define_method(:install) do
        bin.install "initializ"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/initializ/cli/releases/download/v0.3.3/initializ_linux_arm64.tar.gz"
      sha256 "0ffeeba44d644c5af0105a81ae0192d5cf3f74e3a80bc4b3d5833878af20cd36"
      define_method(:install) do
        bin.install "initializ"
      end
    end
  end

  test do
    system "#{bin}/initializ", "version"
  end
end
