# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Initializ < Formula
  desc "Initializ platform CLI for CI pipelines"
  homepage "https://initializ.ai"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/initializ/cli/releases/download/v0.3.1/initializ_darwin_amd64.tar.gz"
      sha256 "4f936359792e82882b924e1d7502244bf0620d1af52453002596572b86d90b03"

      define_method(:install) do
        bin.install "initializ"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/initializ/cli/releases/download/v0.3.1/initializ_darwin_arm64.tar.gz"
      sha256 "76af58965f49241c89f2222f2a28456c8a3a7ca593e02639a87e9805238aa359"

      define_method(:install) do
        bin.install "initializ"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/initializ/cli/releases/download/v0.3.1/initializ_linux_amd64.tar.gz"
      sha256 "fe9e19d8d79adc7f9495ff0939383419464f404ea3a5782194afa7bea96e2276"
      define_method(:install) do
        bin.install "initializ"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/initializ/cli/releases/download/v0.3.1/initializ_linux_arm64.tar.gz"
      sha256 "8fc7bc1bdab5cb7c0d775902f7e48ca819663b470749ea200000c0f636d588a4"
      define_method(:install) do
        bin.install "initializ"
      end
    end
  end

  test do
    system "#{bin}/initializ", "version"
  end
end
